{{- $secretManagerItems := include "common.secretManagerItems" . -}}
{{- $data := fromJson (printf "{\"items\": %s}" $secretManagerItems) -}}
# TYPE: {{ typeOf $data }}
# TYPE ITEMS: {{ typeOf $data.items }}
