apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "robustName" .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
  annotations:
    kubectl.kubernetes.io/default-container: {{ template "robustName" .Release.Name }}
    {{- if .Values.gitSha }}
    gimlet.io/git-sha: {{ .Values.gitSha }}
    v1alpha1.opensca.dev/version.sha: {{ .Values.gitSha }}
    {{- end }}
    {{- if .Values.gitBranch }}
    gimlet.io/git-branch: {{ .Values.gitBranch }}
    v1alpha1.opensca.dev/version.branch: {{ .Values.gitBranch }}
    {{- end }}
spec:
  {{- if not (or (hasKey .Values.autoscaling "cpuAverageUtilization") (hasKey .Values.autoscaling "memoryAverageUtilization")) }}
  replicas: {{ if (hasKey .Values "replicas") }}{{ .Values.replicas }}{{ else }}1{{ end }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm-chart.selectorLabels" . | nindent 6 }}
  strategy:
    {{- if kindIs "string" .Values.strategy }}
    type: {{ .Values.strategy }}
    {{- else }}
    type: {{ .Values.strategy.type | default "RollingUpdate" }}
    {{- if eq (.Values.strategy.type | default "RollingUpdate") "RollingUpdate" }}
    {{- if hasKey .Values.strategy "rollingUpdate" }}
    rollingUpdate:
      {{- with .Values.strategy.rollingUpdate.maxSurge }}
      maxSurge: {{ . }}
      {{- end }}
      {{- if hasKey .Values.strategy.rollingUpdate "maxUnavailable" }}
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
      {{- end }}
    {{- else }}
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    {{- end }}
    {{- end }}
  {{- end }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.gitSha }}
        gimlet.io/git-sha: {{ .Values.gitSha }}
        {{- end }}
        {{- if .Values.gitRepository }}
        gimlet.io/git-repository: {{ .Values.gitRepository }}
        {{- end }}
      labels:
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "helm-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- $podSpecTpl := include "common.podSpec.tpl" . | fromYaml }}
      {{- $podSpec := mergeOverwrite $podSpecTpl .Values.podSpec }}
      {{- toYaml $podSpec | nindent 6 }}
