{{- if .Values.secrets.secretManager }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ template "common.robustName" .Release.Name }}-csi
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: {{ .Values.secrets.secretManager.name }}
          objectType: secretsmanager
          jmesPath:
            {{- range .Values.secrets.secretManager.keys }}
            - path: {{ . }}
              objectAlias: {{ . }}
            {{- end }}
  secretObjects:
  - secretName: {{ template "common.robustName" .Release.Name }}-csi
    type: Opaque
    data:
    {{- range .Values.secrets.secretManager.keys }}
    - objectName: {{ . }}
      key: {{ . }}
    {{- end }}
{{- end }}
