{{- $secretManagerItems := include "common.secretManagerItems" . | trim -}}
{{- if and $secretManagerItems (ne $secretManagerItems "[]") -}}
{{- $data := fromJson (printf "{\"items\": %s}" $secretManagerItems) -}}
{{- range $index, $item := $data.items }}
{{- if $index }}
---
{{- end }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ index $item "volumeName" }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "helm-chart.labels" $ | nindent 4 }}
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: {{ index $item "name" }}
          objectType: secretsmanager
          jmesPath:
            {{- range index $item "keys" }}
            - path: {{ . }}
              objectAlias: {{ . }}
            {{- end }}
  secretObjects:
  - secretName: {{ index $item "volumeName" }}
    type: Opaque
    data:
    {{- range index $item "keys" }}
    {{- $secretKey := . }}
    {{- $envKey := . }}
    {{- $keyMappings := index $item "keyMappings" }}
    {{- if $keyMappings }}
      {{- if hasKey $keyMappings $secretKey }}
        {{- $envKey = index $keyMappings $secretKey }}
      {{- end }}
    {{- end }}
      - key: {{ $envKey }}
        objectName: {{ $secretKey }}
    {{- end }}
{{- end }}
{{- end }}
