{{- if .Values.serviceAccountCreate }}
{{- if .Values.serviceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.serviceAccountCreate.annotations }}
    {{ toYaml . }}
    {{- end }}
  name: {{ .Values.serviceAccount }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
