{{- define "common.podSpec.tpl" -}}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- range . }}
  - name: {{ . }}
  {{- end }}
{{- end }}
securityContext:
  {{- toYaml .Values.podSecurityContext | nindent 2 }}
{{- if .Values.serviceAccount }}
serviceAccountName: {{ .Values.serviceAccount }}
{{- end }}
initContainers:
  {{- range .Values.initContainers }}
  - name:  {{ .name }}
    image: "{{ .image }}:{{ .tag }}"
    imagePullPolicy: {{ .imagePullPolicy | default "IfNotPresent" }}
    {{- include "common.envFromRef.tpl" $ | nindent 4 }}
    {{- if .command }}
    command:
      - {{ $.Values.shell }}
      - -c
      - {{ .command | quote}}
    {{- end }}
    {{- $mounts := list -}}
    {{- range $.Values.volumes }}
    {{- if (or (hasPrefix "shared-" .name) (hasPrefix "init-" .name))}}
    {{- $mounts = append $mounts (dict "mountPath" .path "name" .name) }}
    {{- end }}
    {{- end }}
    {{- $secretManagerItems := include "common.secretManagerItems" $ -}}
    {{- if and $secretManagerItems (ne $secretManagerItems "[]") -}}
    {{- $data := fromJson (printf "{\"items\": %s}" $secretManagerItems) -}}
    {{- range $item := $data.items }}
    {{- $mounts = append $mounts (dict "mountPath" (index $item "mountPath") "name" (index $item "volumeName") "readOnly" true) }}
    {{- end }}
    {{- end }}
    {{- if $mounts }}
    volumeMounts:
    {{- range $mounts }}
    - mountPath: {{ .mountPath }}
      name: {{ .name }}
      {{- if .readOnly }}
      readOnly: true
      {{- end }}
    {{- end }}
    {{- end }}
    {{- if .securityContext }}
    securityContext:
    {{- toYaml .securityContext | nindent 6 }}
    {{- end}}
  {{- end }}
containers:
  {{- $containerTpl := include "common.container.tpl" . | fromYaml }}
  {{- $container := mergeOverwrite $containerTpl .Values.container }}
  - {{ toYaml $container | nindent 4 }}
    {{- include "common.envFromRef.tpl" . | nindent 4 }}
    {{- include "common.volumeMountsRef.tpl" . | nindent 4 }}
  {{- if .Values.sidecar }}
  - name: {{ template "robustName" (include "common.releaseNameOverride" .) }}-sidecar
    securityContext:
      {{- toYaml .Values.securityContext | nindent 6 }}
    image: {{ .Values.sidecar.repository }}:{{ .Values.sidecar.tag }}
    {{- if .Values.sidecar.command }}
    command:
      - {{ .Values.sidecar.shell }}
      - -c
      - {{ .Values.sidecar.command | quote }}
    {{- end }}
    {{- include "common.envFromRef.tpl" . | nindent 4 }}
    {{- include "common.volumeMountsRef.tpl" . | nindent 4 }}
    {{- if .Values.sidecar.resources }}
    resources:
      {{- toYaml .Values.sidecar.resources | nindent 6 }}
    {{- end }}
  {{- end }}
{{- include "common.volumesRef.tpl" . }}
{{- with .Values.nodeSelector }}
nodeSelector:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- if or .Values.spreadAcrossNodes .Values.affinity }}
affinity:
  {{- if .Values.spreadAcrossNodes }}
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: "app.kubernetes.io/instance"
              operator: In
              values:
                - {{ template "robustName" (include "common.releaseNameOverride" .) }}
        topologyKey: "kubernetes.io/hostname"
  {{- end }}
  {{- if .Values.affinity }}
  {{- toYaml .Values.affinity | nindent 2 }}
  {{- end }}
{{- end }}
{{- with .Values.tolerations }}
tolerations:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.dnsPolicy }}
dnsPolicy: {{ . }}
{{- end }}
{{- with .Values.dnsConfig }}
dnsConfig:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.terminationGracePeriodSeconds }}
terminationGracePeriodSeconds: {{ . }}
{{- end }}
{{- end }}