{{- define "common.volumeMountsRef.tpl" -}}
{{- if or (or (or (.Values.secrets.secretManager) (.Values.volumes) (.Values.sealedFileSecrets)) .Values.fileSecrets) .Values.existingFileSecrets -}}
volumeMounts:
  {{- $secretManagerItems := include "common.secretManagerItems" . -}}
  {{- if and $secretManagerItems (ne $secretManagerItems "[]") -}}
  {{- $data := fromJson (printf "{\"items\": %s}" $secretManagerItems) -}}
  {{- range $item := $data.items }}
  - name: {{ index $item "volumeName" }}
    mountPath: {{ index $item "mountPath" }}
    readOnly: true
  {{- end }}
  {{- end }}

{{- range .Values.volumes }}
{{- if not (hasPrefix "init-" .name) }}
  - name: {{ .name }}
    mountPath: {{ .path }}
    {{- if .subPath }}
    subPath: {{ .subPath }}
    {{- end }}
{{- end }}
{{- end }}
{{- range .Values.sealedFileSecrets }}
  - name: {{ .name }}
    mountPath: {{ .path }}
    {{- if .subPath}}
    subPath: {{ .subPath }}
    {{- end }}
    readOnly: true
{{- end }}
{{- range .Values.fileSecrets }}
  - name: {{ .name }}
    mountPath: {{ .path }}
    {{- if .subPath}}
    subPath: {{ .subPath }}
    {{- end }}
    readOnly: true
{{- end }}
{{- range .Values.existingFileSecrets }}
  - name: {{ .name }}
    mountPath: {{ .path }}
    {{- if .subPath}}
    subPath: {{ .subPath }}
    {{- end }}
    readOnly: true
{{- end }}
{{- end }}
{{- end }}

