{{- if .Values.runJobOnDeploy.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-deploy-job-{{ .Release.Revision }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    {{- if .Values.runJobOnDeploy.deleteOnSuccess }}
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- else }}
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- end }}
spec:
  {{- if .Values.runJobOnDeploy.backoffLimit }}
  backoffLimit: {{ .Values.runJobOnDeploy.backoffLimit }}
  {{- end }}
  {{- if .Values.runJobOnDeploy.activeDeadlineSeconds }}
  activeDeadlineSeconds: {{ .Values.runJobOnDeploy.activeDeadlineSeconds }}
  {{- end }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.serviceAccountCreate }}
      serviceAccount: {{ .Release.Name }}
      serviceAccountName: {{ .Release.Name }}
      {{- end }}
      {{- if .Values.serviceAccount }}
      serviceAccount: {{ .Values.serviceAccount }}
      serviceAccountName: {{ .Values.serviceAccount }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      restartPolicy: Never
      containers:
        - name: {{ .Release.Name }}-job
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- if .Values.vars }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- end }}
          {{- if .Values.overrideCommand }}
          command:
            - {{ .Values.shell }}
            - -c
            - {{ .Values.command | quote }}
          {{- end }}
          {{- include "common.envFromRef.tpl" . | nindent 10 }}
          {{- include "common.volumeMountsRef.tpl" . | nindent 10 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- include "common.volumesRef.tpl" . | nindent 6 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}