name: CI
on: [pull_request]
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Helm
        uses: azure/setup-helm@v4
      - name: Install Helm plugins
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest --version v0.7.1 --verify=false
      - name: Lint and Test
        run: |
          make lint
          make test
